# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alejandro/Repos/Personal-Projects/fast-tcp-c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alejandro/Repos/Personal-Projects/fast-tcp-c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alejandro/Repos/Personal-Projects/fast-tcp-c/CMakeFiles /home/alejandro/Repos/Personal-Projects/fast-tcp-c/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alejandro/Repos/Personal-Projects/fast-tcp-c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

#=============================================================================
# Target rules for targets named serializer

# Build rule for target.
serializer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 serializer
.PHONY : serializer

# fast build rule for target.
serializer/fast:
	$(MAKE) -f CMakeFiles/serializer.dir/build.make CMakeFiles/serializer.dir/build
.PHONY : serializer/fast

#=============================================================================
# Target rules for targets named tcp_client

# Build rule for target.
tcp_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tcp_client
.PHONY : tcp_client

# fast build rule for target.
tcp_client/fast:
	$(MAKE) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/build
.PHONY : tcp_client/fast

src/ft_serializer.o: src/ft_serializer.c.o

.PHONY : src/ft_serializer.o

# target to build an object file
src/ft_serializer.c.o:
	$(MAKE) -f CMakeFiles/serializer.dir/build.make CMakeFiles/serializer.dir/src/ft_serializer.c.o
.PHONY : src/ft_serializer.c.o

src/ft_serializer.i: src/ft_serializer.c.i

.PHONY : src/ft_serializer.i

# target to preprocess a source file
src/ft_serializer.c.i:
	$(MAKE) -f CMakeFiles/serializer.dir/build.make CMakeFiles/serializer.dir/src/ft_serializer.c.i
.PHONY : src/ft_serializer.c.i

src/ft_serializer.s: src/ft_serializer.c.s

.PHONY : src/ft_serializer.s

# target to generate assembly for a file
src/ft_serializer.c.s:
	$(MAKE) -f CMakeFiles/serializer.dir/build.make CMakeFiles/serializer.dir/src/ft_serializer.c.s
.PHONY : src/ft_serializer.c.s

src/ft_tcp_socket.o: src/ft_tcp_socket.c.o

.PHONY : src/ft_tcp_socket.o

# target to build an object file
src/ft_tcp_socket.c.o:
	$(MAKE) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/src/ft_tcp_socket.c.o
.PHONY : src/ft_tcp_socket.c.o

src/ft_tcp_socket.i: src/ft_tcp_socket.c.i

.PHONY : src/ft_tcp_socket.i

# target to preprocess a source file
src/ft_tcp_socket.c.i:
	$(MAKE) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/src/ft_tcp_socket.c.i
.PHONY : src/ft_tcp_socket.c.i

src/ft_tcp_socket.s: src/ft_tcp_socket.c.s

.PHONY : src/ft_tcp_socket.s

# target to generate assembly for a file
src/ft_tcp_socket.c.s:
	$(MAKE) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/src/ft_tcp_socket.c.s
.PHONY : src/ft_tcp_socket.c.s

src/ft_util.o: src/ft_util.c.o

.PHONY : src/ft_util.o

# target to build an object file
src/ft_util.c.o:
	$(MAKE) -f CMakeFiles/serializer.dir/build.make CMakeFiles/serializer.dir/src/ft_util.c.o
	$(MAKE) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/src/ft_util.c.o
.PHONY : src/ft_util.c.o

src/ft_util.i: src/ft_util.c.i

.PHONY : src/ft_util.i

# target to preprocess a source file
src/ft_util.c.i:
	$(MAKE) -f CMakeFiles/serializer.dir/build.make CMakeFiles/serializer.dir/src/ft_util.c.i
	$(MAKE) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/src/ft_util.c.i
.PHONY : src/ft_util.c.i

src/ft_util.s: src/ft_util.c.s

.PHONY : src/ft_util.s

# target to generate assembly for a file
src/ft_util.c.s:
	$(MAKE) -f CMakeFiles/serializer.dir/build.make CMakeFiles/serializer.dir/src/ft_util.c.s
	$(MAKE) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/src/ft_util.c.s
.PHONY : src/ft_util.c.s

test/benchmark.o: test/benchmark.c.o

.PHONY : test/benchmark.o

# target to build an object file
test/benchmark.c.o:
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/test/benchmark.c.o
.PHONY : test/benchmark.c.o

test/benchmark.i: test/benchmark.c.i

.PHONY : test/benchmark.i

# target to preprocess a source file
test/benchmark.c.i:
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/test/benchmark.c.i
.PHONY : test/benchmark.c.i

test/benchmark.s: test/benchmark.c.s

.PHONY : test/benchmark.s

# target to generate assembly for a file
test/benchmark.c.s:
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/test/benchmark.c.s
.PHONY : test/benchmark.c.s

test/serializer.o: test/serializer.c.o

.PHONY : test/serializer.o

# target to build an object file
test/serializer.c.o:
	$(MAKE) -f CMakeFiles/serializer.dir/build.make CMakeFiles/serializer.dir/test/serializer.c.o
.PHONY : test/serializer.c.o

test/serializer.i: test/serializer.c.i

.PHONY : test/serializer.i

# target to preprocess a source file
test/serializer.c.i:
	$(MAKE) -f CMakeFiles/serializer.dir/build.make CMakeFiles/serializer.dir/test/serializer.c.i
.PHONY : test/serializer.c.i

test/serializer.s: test/serializer.c.s

.PHONY : test/serializer.s

# target to generate assembly for a file
test/serializer.c.s:
	$(MAKE) -f CMakeFiles/serializer.dir/build.make CMakeFiles/serializer.dir/test/serializer.c.s
.PHONY : test/serializer.c.s

test/tcp_client.o: test/tcp_client.c.o

.PHONY : test/tcp_client.o

# target to build an object file
test/tcp_client.c.o:
	$(MAKE) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/test/tcp_client.c.o
.PHONY : test/tcp_client.c.o

test/tcp_client.i: test/tcp_client.c.i

.PHONY : test/tcp_client.i

# target to preprocess a source file
test/tcp_client.c.i:
	$(MAKE) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/test/tcp_client.c.i
.PHONY : test/tcp_client.c.i

test/tcp_client.s: test/tcp_client.c.s

.PHONY : test/tcp_client.s

# target to generate assembly for a file
test/tcp_client.c.s:
	$(MAKE) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/test/tcp_client.c.s
.PHONY : test/tcp_client.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... benchmark"
	@echo "... serializer"
	@echo "... edit_cache"
	@echo "... tcp_client"
	@echo "... rebuild_cache"
	@echo "... src/ft_serializer.o"
	@echo "... src/ft_serializer.i"
	@echo "... src/ft_serializer.s"
	@echo "... src/ft_tcp_socket.o"
	@echo "... src/ft_tcp_socket.i"
	@echo "... src/ft_tcp_socket.s"
	@echo "... src/ft_util.o"
	@echo "... src/ft_util.i"
	@echo "... src/ft_util.s"
	@echo "... test/benchmark.o"
	@echo "... test/benchmark.i"
	@echo "... test/benchmark.s"
	@echo "... test/serializer.o"
	@echo "... test/serializer.i"
	@echo "... test/serializer.s"
	@echo "... test/tcp_client.o"
	@echo "... test/tcp_client.i"
	@echo "... test/tcp_client.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

